version: "3.8"
services:
  node:
    container_name: "socovos-server"
    build:
      context: .
      dokerfile: Dokerfile
networks:
  socovos-lan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.10.0./24
          gateway: 192.168.10.1